navbar and list of post
Ben0189/Careerlink pull request #32
Opened 2024-10-08 09:27 UTC by stevenfung30

2024-10-08 09:29 UTC, Ben0189 requested changes
dont commit node module

2024-10-15 05:17 UTC, Ben0189 requested changes

2024-10-15 05:17 UTC, Ben0189 commented on package-lock.json
Do we need this ? can you remove this file?

2024-10-15 05:17 UTC, Ben0189 commented on package.json
Do we need this ? can you remove this file?

2024-10-15 05:17 UTC, Ben0189 commented on tailwind.config.js
Do we need this ? can you remove this file?

2024-10-15 05:17 UTC, Ben0189 commented on postcss.config.js
Do we need this ? can you remove this file?

2024-10-15 05:17 UTC, Ben0189 commented on career-link-webui/src/app/listofpost.tsx
rename this file from listofpost to list-of-post

2024-10-15 05:18 UTC, Ben0189 commented
good work , can you also post the UI in this PR?

2024-10-16 01:48 UTC, Ben0189 approved these changes

2024-10-16 02:01 UTC, stevenfung30 commented
![image](https://github.com/user-attachments/assets/4d952878-1357-4252-990b-90bb4f1b945a)

2024-10-16 12:19 UTC, merged